import "./globals.css";
import { Inter } from "next/font/google";
import Topbar from "@/components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className={"dark-theme"}>
        <Topbar />
        {children}
      </body>
    </html>
  );
}
